### ISSUE TITLE
Locatio of payment server

### ISSUE THREAD

**Issue by cdliou** [yidas/line-pay-sdk-php#17]
According to LINE pay document,  the merchant's payment server should not be called outside the inner system, but the architecture of your sdk is all files are in the same server. How to modify the structure in order to meet the requirement?

**Comment by yidas** [comment]
Hi,

You could use this SDK in your payment server but not the web server:
Web server <=> Payment server <=> LINE Pay API server

Regards

**Comment by cdliou** [comment]
Thanks for your reply. But the file  index.php is open to the web, isn't it? So, does we need to move index.php to web server?

**Comment by yidas** [comment]
Hi,

Tools and examples are just sample codes for reference.
You should implement the SDK according to your environment.
