### ISSUE TITLE
Bug: PHP Deprecated Warning - Creation of Dynamic Property

### ISSUE THREAD

**Issue by twpsfirmament** [yidas/line-pay-sdk-php#26]
I encountered a deprecated warning when using the Line Pay SDK to complete a payment action.
 The warning message states: **"PHP Deprecated: Creation of dynamic property".**

Steps to Reproduce:

1. Use the project in a PHP 8 environment.
2. Complete a Line Pay payment action.
3. Observe the PHP deprecated warning in the logs.

Expected Behavior:
The SDK should not produce any deprecated warnings and should handle property creation in a manner compatible with PHP 8.3.1.

Actual Behavior:
A deprecated warning is produced, indicating that the creation of a dynamic property is not supported in PHP 8.3.1.

Environment:

PHP Version: 8.3.1
Application Version: 3.7.1
OS: Windows 10

**Comment by yidas** [comment]
Hi @twpsfirmament,

Thank you for the feedback.

This issue has been resolved from [v3.8.0](https://github.com/yidas/line-pay-sdk-php/releases/tag/3.8.0), Please provide feedback if you encounter any further issues.
